title: Alicja's thoughts
description: A blog on learning and programming ideas

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alicja.dev" # the base hostname & protocol for your site
author: Alicja Raszkowska

markdown: kramdown
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-feed

languages: ["en", "pl"]

show_drafts: false
future: true

sass:
  style: compressed

highlighter: rouge

cdn_path: https://s3.eu-west-2.amazonaws.com/photos-trueskawka/photos