title: Alicja Raszkowska

baseurl: "/mini-jekyll" # the subpath of your site, e.g. /blog
url: "https://trueskawka.github.io" # the base hostname & protocol for your site

markdown: kramdown
plugins:
  - jekyll-multiple-languages-plugin

languages: ["en", "pl"]

show_drafts: false
future: true